In [1]:
import pandas as pd

df = pd.read_json(r"C:\Users\Gaddam Anushka\Downloads\[PUB] India_runs_data_and_ai_challenge\[PUB] India_runs_data_and_ai_challenge\India_runs_data_and_ai_challenge\candidates.jsonl", lines=True)

In [2]:
AI_SKILLS = {
    "Python",
    "Machine Learning",
    "Deep Learning",
    "NLP",
    "LLM",
    "Fine-tuning LLMs",
    "Embeddings",
    "Vector Databases",
    "Pinecone",
    "Weaviate",
    "Qdrant",
    "Milvus",
    "FAISS",
    "Elasticsearch",
    "OpenSearch",
    "Spark",
    "PySpark",
    "Airflow",
    "SQL",
    "Ranking",
    "Recommendation Systems",
    "Retrieval",
    "Transformers"
}

In [3]:
def count_ai_skills(skills):

    names = [s["name"] for s in skills]

    return len(set(names).intersection(AI_SKILLS))

df["ai_skill_score"] = df["skills"].apply(count_ai_skills)

In [4]:
def experience_score(x):

    if 5 <= x <= 9:
        return 10

    elif 4 <= x < 5:
        return 8

    elif 9 < x <= 11:
        return 8

    elif 2 <= x < 4:
        return 5

    else:
        return 2

df["experience_score"] = df["profile"].apply(
    lambda x: experience_score(x["years_of_experience"])
)

In [5]:
df["open_to_work_bonus"] = df["redrob_signals"].apply(
    lambda x: 5 if x["open_to_work_flag"] else 0
)

In [6]:
df["github_score"] = df["redrob_signals"].apply(
    lambda x: max(x["github_activity_score"], 0)
)

In [7]:
df["response_score"] = df["redrob_signals"].apply(
    lambda x: x["recruiter_response_rate"] * 10
)

In [8]:
df["profile_score"] = df["redrob_signals"].apply(
    lambda x: x["profile_completeness_score"] / 10
)

In [9]:
df["final_score"] = (
      df["ai_skill_score"] * 5
    + df["experience_score"] * 3
    + df["github_score"] * 1.5
    + df["response_score"] * 2
    + df["profile_score"] * 1
    + df["open_to_work_bonus"]
)

In [13]:
top = df.sort_values(
    "final_score",
    ascending=False
)

top[[
    "candidate_id",
    "final_score"
]].head(20)

       candidate_id  final_score
2024   CAND_0002025       249.53
18498  CAND_0018499       229.20
16162  CAND_0016163       225.85
66998  CAND_0066999       221.52
14439  CAND_0014440       218.93
49537  CAND_0049538       215.89
50875  CAND_0050876       215.73
18721  CAND_0018722       213.59
71973  CAND_0071974       213.11
51614  CAND_0051615       211.03
17959  CAND_0017960       210.11
99805  CAND_0099806       208.56
76162  CAND_0076163       207.67
47720  CAND_0047721       206.41
74734  CAND_0074735       206.24
20707  CAND_0020708       206.19
24989  CAND_0024990       205.75
39382  CAND_0039383       205.70
61264  CAND_0061265       202.15
86021  CAND_0086022       201.81

In [14]:
# Weighted keywords based on importance in the JD
KEYWORD_WEIGHTS = {
    "ranking": 8,
    "retrieval": 8,
    "recommendation": 8,
    "embedding": 7,
    "embeddings": 7,
    "vector": 6,
    "llm": 7,
    "transformer": 6,
    "fine tuning": 6,
    "rag": 6,
    "machine learning": 5,
    "deep learning": 5,
    "nlp": 5,
    "search": 4,
    "spark": 3,
    "airflow": 3,
    "sql": 2,
    "python": 4,
    "pytorch": 4,
    "tensorflow": 4
}

def weighted_ai_score(history):
    score = 0

    for job in history:
        desc = job.get("description", "").lower()

        for keyword, weight in KEYWORD_WEIGHTS.items():
            if keyword in desc:
                score += weight

    return score

df["career_ai_score"] = df["career_history"].apply(weighted_ai_score)

In [15]:
df[["candidate_id", "career_ai_score"]].sort_values(
    "career_ai_score",
    ascending=False
).head(20)

       candidate_id  career_ai_score
92277  CAND_0092278              119
39753  CAND_0039754              109
9690   CAND_0009691              108
87629  CAND_0087630              108
18498  CAND_0018499              102
77336  CAND_0077337              101
41610  CAND_0041611               95
30952  CAND_0030953               90
55904  CAND_0055905               86
55991  CAND_0055992               86
46063  CAND_0046064               86
50875  CAND_0050876               84
94758  CAND_0094759               81
7411   CAND_0007412               80
88024  CAND_0088025               79
81845  CAND_0081846               78
33860  CAND_0033861               75
71973  CAND_0071974               75
79386  CAND_0079387               74
44854  CAND_0044855               74

In [18]:
KEYWORD_WEIGHTS = {
    "ranking": 8,
    "retrieval": 8,
    "recommendation": 8,
    "embedding": 7,
    "embeddings": 7,
    "vector": 6,
    "llm": 7,
    "transformer": 6,
    "fine tuning": 6,
    "rag": 6,
    "machine learning": 5,
    "deep learning": 5,
    "nlp": 5,
    "search": 4,
    "spark": 3,
    "airflow": 3,
    "sql": 2,
    "python": 4,
    "pytorch": 4,
    "tensorflow": 4
}

def weighted_ai_score(history):

    full_text = " ".join(
        job.get("description", "").lower()
        for job in history
    )

    score = 0

    for keyword, weight in KEYWORD_WEIGHTS.items():
        if keyword in full_text:
            score += weight

    return score

df["career_ai_score"] = df["career_history"].apply(weighted_ai_score)
df["career_ai_score"].describe()

count    100000.000000
mean          4.560010
std           4.862953
min           0.000000
25%           0.000000
50%           3.000000
75%           8.000000
max          67.000000
Name: career_ai_score, dtype: float64

In [19]:
df.columns.tolist()

['candidate_id',
 'profile',
 'career_history',
 'education',
 'skills',
 'certifications',
 'languages',
 'redrob_signals',
 'ai_skill_score',
 'experience_score',
 'open_to_work_bonus',
 'github_score',
 'response_score',
 'profile_score',
 'final_score',
 'career_ai_score']

In [20]:
df["headline"] = df["profile"].apply(lambda x: x["headline"])
df["experience"] = df["profile"].apply(lambda x: x["years_of_experience"])

In [21]:
top = df.sort_values("career_ai_score", ascending=False)

top[[
    "candidate_id",
    "career_ai_score",
    "headline",
    "experience"
]].head(20)

,candidate_id,career_ai_score,headline,experience
39753,CAND_0039754,67,Senior Applied Scientist | Building AI-native ...,16.2
92277,CAND_0092278,61,Senior NLP Engineer | Building AI-native searc...,6.8
77336,CAND_0077337,60,Staff Machine Learning Engineer | Building AI-...,7.0
55904,CAND_0055905,59,"Senior Machine Learning Engineer | LLMs, RAG, ...",8.1
81845,CAND_0081846,59,"Lead AI Engineer | LLMs, RAG, Vector Search | ...",6.7
41610,CAND_0041611,59,Staff Machine Learning Engineer | Building AI-...,6.4
46063,CAND_0046064,55,"Senior NLP Engineer | LLMs, RAG, Vector Search...",8.9
79386,CAND_0079387,54,AI Engineer | Applied ML | Building intelligen...,6.9
44854,CAND_0044855,54,"Senior Data Scientist | ML, NLP, Recommendatio...",6.6
33860,CAND_0033861,54,Senior NLP Engineer | Building AI-native searc...,8.0
55991,CAND_0055992,54,"AI Engineer | Search, Ranking & Retrieval",16.9
30952,CAND_0030953,54,"Search Engineer | ML, NLP, Recommendation Systems",7.8
86150,CAND_0086151,48,"Recommendation Systems Engineer | Search, Rank...",7.7
96171,CAND_0096172,48,NLP Engineer | Applied ML | Building intellige...,5.2
26531,CAND_0026532,48,"Recommendation Systems Engineer | Search, Rank...",4.8
81685,CAND_0081686,48,Search Engineer | Applied ML | Building intell...,6.0
75248,CAND_0075249,48,"Applied ML Engineer | Search, Ranking & Retrieval",6.2
30347,CAND_0030348,48,"Machine Learning Engineer | ML, NLP, Recommend...",4.5
13612,CAND_0013613,48,"Machine Learning Engineer | ML, NLP, Recommend...",4.7
54122,CAND_0054123,48,"Applied ML Engineer | Search, Ranking & Retrieval",4.7

In [1]:
!pip install sentence-transformers
!pip show sentence-transformers

Collecting sentence-transformers
  Using cached sentence_transformers-5.6.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sentence-transformers) (5.5.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sentence-transformers) (1.9.2)
Requirement already satisfied: torch>=1.11.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sentence-transformers) (2.11.0)
Requirement already satisfied: numpy>=1.20.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sentence-transformers) (2.3.5)
Collecting scikit-learn>=0.22.0 (from sentence-transformers)
  Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: scipy>=1.0.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sentence-transformers) (1.17.1)
Requirement already satisfied: typing_extensions>=4.5.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sentence-transformers) (4.14.1)
Requirement already satisfied: tqdm>=4.0.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: packaging>=20.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.12.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: anyio in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.12.0)
Requirement already satisfied: certifi in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2025.8.3)
Requirement already satisfied: httpcore==1.* in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.10)
Requirement already satisfied: h11>=0.16 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Collecting joblib>=1.4.0 (from scikit-learn>=0.22.0->sentence-transformers)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn>=0.22.0->sentence-transformers)
  Downloading narwhals-2.22.1-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn>=0.22.0->sentence-transformers)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: setuptools<82 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from tqdm>=4.0.0->sentence-transformers) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: click>=8.2.1 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (14.2.0)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Using cached sentence_transformers-5.6.0-py3-none-any.whl (596 kB)
Downloading scikit_learn-1.9.0-cp313-cp313-win_amd64.whl (8.2 MB)
   ---------------------------------------- 0.0/8.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.2 MB 12.3 MB/s eta 0:00:01
   --------------- ------------------------ 3.1/8.2 MB 12.6 MB/s eta 0:00:01
   ------------------------ --------------- 5.0/8.2 MB 10.4 MB/s eta 0:00:01
   ----------------------------- ---------- 6.0/8.2 MB 9.4 MB/s eta 0:00:01
   ---------------------------------- ----- 7.1/8.2 MB 7.9 MB/s eta 0:00:01
   ------------------------------------- -- 7.6/8.2 MB 7.1 MB/s eta 0:00:01
   ---------------------------------------- 8.2/8.2 MB 6.3 MB/s  0:00:01
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Downloading narwhals-2.22.1-py3-none-any.whl (454 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, narwhals, joblib, scikit-learn, sentence-transformers

   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   -------- ------------------------------- 1/5 [narwhals]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ---------------- ----------------------- 2/5 [joblib]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   ------------------------ --------------- 3/5 [scikit-learn]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   -------------------------------- ------- 4/5 [sentence-transformers]
   ---------------------------------------- 5/5 [sentence-transformers]

Successfully installed joblib-1.5.3 narwhals-2.22.1 scikit-learn-1.9.0 sentence-transformers-5.6.0 threadpoolctl-3.6.0

[notice] A new release of pip is available: 26.0 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Name: sentence-transformers
Version: 5.6.0
Summary: Embeddings, Retrieval, and Reranking
Home-page: https://www.SBERT.net
Author:
Author-email: Nils Reimers <info@nils-reimers.de>, Tom Aarsen <tom.aarsen@huggingface.co>
License-Expression: Apache-2.0
Location: C:\Users\Gaddam Anushka\AppData\Local\Programs\Python\Python313\Lib\site-packages
Requires: huggingface-hub, numpy, scikit-learn, scipy, torch, tqdm, transformers, typing_extensions
Required-by:

In [6]:
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [7]:
model = SentenceTransformer("all-MiniLM-L6-v2")

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [9]:
job_description = """
Senior AI Engineer.

Looking for engineers experienced in:

Python
Machine Learning
Deep Learning
NLP
LLMs
Embeddings
Vector Databases
Retrieval
Ranking
Recommendation Systems
Search Systems
Fine-tuning
Hybrid Search
Production AI
Evaluation Metrics
Spark
Airflow
SQL

Candidates should have production AI experience, product-company background,
and have built ranking/search/recommendation systems.
"""

ModuleNotFoundError: No module named 'pandas'

In [15]:
job_embedding = model.encode(job_description)

candidate_embeddings = model.encode(
    df["candidate_text"].tolist(),
    show_progress_bar=True,
    batch_size=64
)

NameError: name 'df' is not defined

In [ ]:
print(model)

In [ ]:
def build_candidate_text(row):

    summary = row["profile"].get("summary", "")

    headline = row["profile"].get("headline", "")

    skills = " ".join([s["name"] for s in row["skills"]])

    career = " ".join([job.get("description", "") for job in row["career_history"]])

    return headline + " " + summary + " " + skills + " " + career

df["candidate_text"] = df.apply(build_candidate_text, axis=1)

In [ ]:
df["candidate_text"].head()

In [ ]:
print(type(model))

In [ ]:
df["candidate_text"].head(3)

In [ ]:
text = "Python Machine Learning NLP"

embedding = model.encode(text)

print(embedding.shape)

In [ ]:
import sys
print(sys.version)